### PR TITLE
Use pihole checkout for development checkout

### PR DESCRIPTION
**Pull request by diginc**
And add FTL

### CODE REVIEW

**Comment by HorayNarea** [comment]
FTL is not starting correctly since I updated to the newest dev-image (which contains this merged PR)
It just keeps spamming the log with "Starting pihole-FTL" and never gets started -> no data shown in the webinterface

**Comment by HorayNarea** [comment]
seems like the directory for its socket is missing:
```
docker exec -it pihole /bin/bash
ls /var/run/pihole
ls: cannot access '/var/run/pihole': No such file or directory
```

**Comment by diginc** [comment]
#227 Had a fix for that one @HorayNarea

**Comment by HorayNarea** [comment]
Well my docker host is an Archlinux… :D

**Comment by diginc** [comment]
Is it doing any sort of weird /var mounts like described in #217 ?  That is what fedora was doing and it was breaking the expected directory structure of /var.  You could do a docker inspect on your container to see if there's a volume mount for /var that you did not add.

```
docker pull diginc/pi-hole:debian_dev ; docker run -it -e ServerIP="1.2.3.4" -v /dev/null:/etc/pihole/adlists.default -e PYTEST="True" diginc/pi-hole:debian_dev bash
...
root@f0adfa825680:/# ls -lat /var/run/pihole
total 8
drwxr-xr-x  2 root root 4096 Jan 31 19:50 .
drwxr-xr-x 11 root root 4096 Jan 31 19:50 ..
srwxr-xr-x  1 root root    0 Jan 31 19:50 FTL.sock
```

**Comment by HorayNarea** [comment]
Nope, just `/etc/pihole` and `/etc/dnsmasq.d`
bildschirmfoto vom 2018-01-31 21-05-25

**Pull request merged**
