### PR TITLE
Attempting to update base image to debian stretch

### PR DESCRIPTION
**Pull request by halkeye**
This is mostly to fix https://github.com/pi-hole/pi-hole/issues/1392 for me, which shows we need a more modern version of dnsmasq.
the one in jessie is a couple years old now.

I am not sure if I should be updating the docker templates, but they were in the branch to start with

### CODE REVIEW

**Comment by halkeye** [comment]
@diginc I'm not sure if anything in https://github.com/diginc/docker-pi-hole/issues/196 is impacted, I don't think so though.

**Comment by halkeye** [comment]
https://discourse.pi-hole.net/t/running-dnscrypt-and-dnssec/1463/8 mentions another way of forcing dnsmasq to be pulled from stretch but I think a full base upgrade is better than trying to mix versions.

**Comment by halkeye** [comment]
I have no idea what that test is testing? I'm guessing if dnsmasq fails when a hostname/name is provided instead of an IP?

**Comment by diginc** [comment]
#211 already started using stretch.

**Comment by diginc** [comment]
I think tests are failing for the same reason my dev branch update did.  The non interactive is not persisting down into the install script and it still hangs on the perl TERM not set error

```
+ debconf-apt-progress -- apt-get --yes --no-install-recommends install apt-utils dialog dhcpcd5 git whiptail
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
```

Try this build local to confirm

`./Dockerfile.py --no-build ; docker build  --pull --no-cache --cache-from="diginc/pi-hole:debian_amd64,pi-hole:debian_amd64" -f Dockerfile_debian_amd64 -t pi-hole:debian_amd64 .`

**Comment by diginc** [comment]
Actually looks like you resolved that already.  You might try merging my changes from #211 into your and see if that resolves your failures.

**Comment by halkeye** [comment]
Yea the renaming of the apt module wasn't working cause stretch didn't have
systemctl


I'll try merging when I get home.

**Comment by diginc** [comment]
I've merged your commits into #211 along with the fixes to the test.

**Pull request closed without merging**
