### PR TITLE
Prerelease of FTLDNS image

### PR DESCRIPTION
**Pull request by diginc**
## Description
Pi-Hole FTLDNS pre release changes

## Motivation and Context
Prep work to confirm the image is ready for FTLDNS

## How Has This Been Tested?
pytests updated.  Running resulting image for personal use.

## Types of changes
New version!

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by diginc** [comment]
Available test images:

For [x86](https://hub.docker.com/r/diginc/pi-hole/tags/)
  - `diginc/pi-hole:prerelease`
- For [ARM](https://hub.docker.com/r/diginc/pi-hole-multiarch/tags/) per https://github.com/diginc/docker-pi-hole/issues/295
  - `diginc/pi-hole-multiarch:debian_aarch64_prerelease`
  - `diginc/pi-hole-multiarch:debian_armhf_prerelease`

**Comment by diginc** [comment]
Reminder: contingent on the next release not using block pages, but NULL DNS responses by default, I may remove the validation of "ServerIP" being set and exiting the container startup when not set since it will not be required anymore.

**Comment by nightah** [comment]
Looks like some of the default behaviour like grabbing and updating the default adlists doesn't work in this pre-release, not sure if that's by design or an oversight.

Happy to run it for longer and provide other feedback if necessary.

**Comment by diginc** [comment]
There are [no adlists by default in the new FTLDNS pi-hole installer](https://github.com/pi-hole/pi-hole/blob/FTLDNS/automated%20install/basic-install.sh#L992), there is a prompt for users to select the current 'recommended' ones they want to opt into.  I haven't made an equivalent way for users to opt-in to the lists of ads.  I'll add something for this and do more checking on the updating.

Once the lists are selected they seemed to update OK during container startup and the web interface, I'm just re-using my old 3.3.1 container volume data to seed the lists in all real world tests so far though.

I saw the pihole-FTL restart errors too, I am pushing a fix for those now.

**Comment by nightah** [comment]
I had previously specified the dns server for the pi-hole container as `127.0.0.1` and that seemed to have issues when I re-used my old container volume. When I removed that setting things seem to be working again.

Few other issues I seem to encounter with the new version:

- Query Log is stuck on `Processing...` and does not show any recent queries.
- Tools -> Tail pihole.log results in the following error: `Failed to open log file. Check permissions!`
I suspect this is because it's running as UID/GID `root / dip` vs `root / root`

All the other features seem to more or less work appropriately with my limited testing.

**Comment by nightah** [comment]
Also noticed that the both Query Types and Queries answered by pie charts on the Dashboard appear to have missing pieces.

You can see [here](https://i.imgur.com/f17sYqH.png) what I mean. Again could be unrelated but that doesn't seem to be an issue on the main release. Happy to lodge this upstream if you're experiencing the same problem.

**Comment by diginc** [comment]
Moving this branch to match pi-hole's release branch name scheme (release/v4.0) and made a new pull request: #300

**Pull request closed without merging**
