### PR TITLE
update pi-hole to FTL to 2.11.1

### PR DESCRIPTION
**Pull request by mr-bolle**
https://github.com/pi-hole/FTL/releases/tag/v2.11.1

### CODE REVIEW

**Comment by diginc** [comment]
Needs to be merged to dev prior to master.

**Comment by mr-bolle** [comment]
ok - i download the last release into this docker container. And see a issue after i put `pihole -up`
I will try to use your other branch, or a other Linux distripution.  Next time i will use the dev branch, for the pull request.

> 
> bash-4.3# pihole -up
> ::: Checking for updates...
> ::: Pi-hole Core:   up to date
> ::: FTL:            update available
> :::
> ::: FTL out of date
> :::
> ::: Downloading latest version of FTL...
> :::  Detected x86_64 architecture
> :::  Installing FTL... sha1sum: unrecognized option: status
> BusyBox v1.27.1 (2017-08-05 22:04:53 GMT) multi-call binary.
> 
> Usage: sha1sum [-c[sw]] [FILE]...
> 
> Print or check SHA1 checksums
> 
>         -c      Check sums against list in FILEs
>         -s      Don't output anything, status code shows success
>         -w      Warn about improperly formatted checksum lines
> failed (download of binary from Github failed)
> sha1sum -c /tmp/pihole-FTL-linux-x86_64.sha1
> pihole-FTL-linux-x86_64: OK

**Comment by diginc** [comment]
`pihole -up` replaced [the fix](https://github.com/diginc/docker-pi-hole/blob/e037ca86af941910c17dcfcde0efbd24aca453c6/install.sh#L26) I implemented (with stock code).  alpine/busybox sha1sum flags are different so I update them with sed there.

The build error your travis CI build is running into is here: https://travis-ci.org/diginc/docker-pi-hole/builds/285635730?utm_source=github_status&utm_medium=notification

Ignore any subsequent failures after the image building, these are the only ones that matter:

```
test/test_000_build_containers.py::test_build_pihole_image[debian-amd64] PASSED
test/test_000_build_containers.py::test_build_pihole_image[debian-armhf] FAILED
test/test_000_build_containers.py::test_build_pihole_image[debian-aarch64] FAILED
test/test_000_build_containers.py::test_build_pihole_image[alpine-amd64] FAILED
test/test_000_build_containers.py::test_build_pihole_image[alpine-armhf] FAILED
test/test_000_build_containers.py::test_build_pihole_image[alpine-aarch64] FAILED
```

Until those pass the subsequent tests will fail with images not found (I need to optimize that still)

If you search the log you'll see `standard_init_linux.go:178: exec user process caused "exec format error"` is the primary build failure cause repeatedly.  Typically that's a mismatch of architecture so I'm wondering if the pihole installer didn't detect docker's architecture correctly.  Which is strange because this worked on dev a couple days ago: https://travis-ci.org/diginc/docker-pi-hole/builds/283816777

**Comment by diginc** [comment]
I figured it out.  The fact you initially branched/forked off master made travis use the master .travis-ci.yml config.  When I changed it to 'dev' base for the pull request it kept using master's config but ran dev's tests - which won't work without devs' recently updated config.

I'm pretty sure there's no problem with the code so I'll merge.

I might not get an official image released with this change until this weekend unfortunately.

**Pull request merged**
