### PR TITLE
armhf support

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by diginc** [comment]
Sweet!  Funny timing because I was working on the same thing last night for #2, I just didn't get my docker image running due to an error when running with `docker run -d`.  That might not be related to the image its self though since I'm running hypriot for the first time.  I'll try this out tonight to see if this is any different.

Are you using hypriot and able to run the built image successfully?

**Comment by soredake** [comment]
No, i tested build and run on raspberrypi2

**Comment by ufud-org** [comment]
Well, I've modified debian.docker and docker_run.sh as well as added an armhf version of tini to my cloned repo of yours. I'm building it on Hypriot 0.8 using a Raspberry Pi 3. Works very well. Let me know, if you are interested in the changes I've made (not much, really).

**Comment by ufud-org** [comment]
I've successfully built your code doing minor changes debian.docker and docker_run.sh. I've also built an armhf version of tini. Built it on hypriot 0.8 on a Pi3. Let me know if you are interested in the changes I've made (not much, really).

**Comment by diginc** [comment]
@soredake - Sorry for the delay in getting back to you - when I tested this I think the path on line 55 was a missing file (I think you meant `COPY ./debian-armhf/start.sh /`).  Also could you re-open this pull request against the [`dev` branch](https://github.com/diginc/docker-pi-hole/tree/dev)?  

Master branch auto-rebuilds all the docker images again so I'm trying to only merge to it when changes actually occur to the docker images (I'll need to add in new test/builds for arm)

@ufud-org cool, I'd be curious to see what you have!  Please do open a pull request (preferably to the [`dev` branch](https://github.com/diginc/docker-pi-hole/tree/dev) as base).  

I wanted to clean/optimize things a little bit before adding 2 more images for arm, like by not adding another duplicate (less duplication = less maintenance) `start.sh` script (by using ENV vars in different Dockerfiles.  I also wanted to test out using [ONBUILD](https://docs.docker.com/engine/reference/builder/#/onbuild) to also reduce duplicative Dockerfile code.  I'd be OK doing this after merging an initial dockerfile for arm though.

**Comment by diginc** [comment]
I merged #30 so you probably don't need to re-open the pull request against dev branch.

**Comment by ufud-org** [comment]
> I merged #30 so you probably don't need to re-open the pull request against dev branch.
that's great news. can't wait to beta-test this once it comes available in master.

**Pull request closed without merging**
