### PR TITLE
3.0.1 fix

### PR DESCRIPTION
**Pull request by remonlam**
Small fix to make 3.0.1 work for the ARM image.

### CODE REVIEW

**Comment by diginc** [comment]
Not based against `dev` branch, which also already has a lot of 3.0.1 and FTL work on it.

**Comment by remonlam** [comment]
Ah sorry, will take a look at dev, thanks!

**Comment by diginc** [comment]
the `diginc/pi-hole:arm_dev` tag is available for testing too.

production release coming in 4-5 hours https://github.com/diginc/docker-pi-hole/issues/131

**Comment by remonlam** [comment]
@diginc ok thanks, will use that one!

**Pull request closed without merging**
