### PR TITLE
use dnsmasq-dnssec

### PR DESCRIPTION
**Pull request by markschultz**
allows to enable dnssec in pi-hole settings

### CODE REVIEW

**Comment by diginc** [comment]
How does this impact the users of the container?  [The tests appear to be failing](https://travis-ci.org/diginc/docker-pi-hole/builds/238242736?utm_source=github_status&utm_medium=notification) because this package change doesn't have the dnsmasq user installed like the standard dnsmasq package.

**Comment by markschultz** [comment]
well pi-hole has a setting "Enable DNSSEC" currently if you enable that dnsmasq will continuously crash as it ws compiled without dnssec support. apologies, i couldn't actually tell what the error was. i've manually installed the `dnsmasq-dnssec` package on my local container and i can successfully enable that setting now.

**Comment by diginc** [comment]
Gotcha, I get it now.  Debian probably already has the dnssec package since it uses the official installer so there probably isn't a change needed for those versions of the image.

If you didn't uninstall dnsmasq from your container then it sounds like dnsmasq-dnssec is an extra package and not a replacement for dnsmasq.  You should leave dnsmasq in the apk add command and just add the dnssec package after it.

I accidently deleted the dev branch while cleaning up merged branches.  I re-created it and set it as the target for merging.

**Comment by diginc** [comment]
looks like I was wrong.  dnsmasq-dnssec and dnsmasq are just different conflicting packages on alpine apparently.  the latter comes with the dnsmasq user.

**Comment by shaf** [comment]
Catered for in PR #175 

Cheers

**Pull request closed without merging**
